// Negative / edge-case suite — Login
// Auto-generated by QATestFlow (F20). Each test feeds ONE hostile value and
// asserts the app REJECTS it. A fully passing suite means your input
// validation holds; a FAILURE means bad/malicious input was accepted.
import { test, expect } from '@playwright/test'

// Base URL — override per environment in CI with the BASE_URL env var.
test.use({ baseURL: process.env.BASE_URL || "https://www.saucedemo.com", testIdAttribute: "data-test" })

test("Username rejects SQL injection", async ({ page }) => {
  // Go to https://www.saucedemo.com/
  await page.goto("/")

  // Type "standard_user" into Username
  await page.getByTestId('username').fill("standard_user")

  // Type "••••••••" into Password
  await page.getByTestId('password').fill(process.env.PASSWORD ?? '') // password field — set the PASSWORD env var

  // Click Login
  await page.getByTestId('login-button').click()

  // ✋ Negative test: the app should REJECT this input, so the happy-path
  // success check must NOT pass. If it passes, hostile input was accepted.
  let reachedSuccess = true
  try {
    await expect(page.getByText('Products')).toBeVisible()
  } catch {
    reachedSuccess = false
  }
  expect(reachedSuccess, "app accepted \"' OR 1=1 --\" in Username — expected it to be rejected").toBe(false)
})
