// =====================================================================
// THE PAGE → ELECTRON TRUST BOUNDARY  (audit finding QF-002)
// =====================================================================
// WHAT WENT WRONG
//
// The recorder observer runs inside the page being tested and posts its events
// up to the top frame, where a preload relay forwards them to main over IPC.
// That relay used to be four lines:
//
//     if (data.__qaflow === true && typeof data.channel === 'string')
//       ipcRenderer.send(data.channel, data.payload)
//
// Any script on the tested page could post that shape. So a tested website
// could:
//
//   · insert fabricated steps into the user's recording (the audit proved this
//     with a step literally labelled "Forged by page"), and
//   · reach ANY `ipcMain.on` channel in the application, with any payload —
//     including `recorder:upload`, whose handler copies caller-supplied file
//     paths into the local test library.
//
// The second one is the part that matters. A page choosing its own IPC channel
// name is not a recorder bug, it is a privilege boundary that isn't there.
//
// WHAT THIS MODULE DOES
//
// It is the boundary. Every message arriving from the page world must:
//
//   1. name a channel on a small ALLOWLIST — and `recorder:upload` is
//      deliberately NOT on it, because the relay produces upload events itself
//      from trusted isolated-world file events (see preload/recorder.ts);
//   2. carry the current recording NONCE, which main re-rolls per session and
//      hands only to the isolated-world relay;
//   3. match a strict SCHEMA, after which a clean object is rebuilt from known
//      keys only — nothing the page sent travels onward by reference;
//   4. stay within size limits, so a hostile page cannot post a 500MB string
//      and take the app down instead.
//
// ── WHAT THIS DOES *NOT* FIX, STATED PLAINLY ────────────────────────────
// The observer runs in the page's own JavaScript world. Anything reachable
// from that world is reachable by the page, so a determined hostile page that
// waits for a genuine recorder message can still read the nonce off it and
// forge a WELL-FORMED step on an allowlisted channel. This module removes the
// privilege escalation (arbitrary channels, arbitrary upload paths) and raises
// forgery from "unconditional, trivial" to "requires observing a live
// recording in progress". It does not make forgery impossible.
//
// Closing it completely means moving the observer out of the page world into
// an isolated world with a CDP binding back to main — a real change to the
// injection architecture, not a patch to this file.
// =====================================================================

/** The only channels a page-world observer may ever speak on.
 *
 *  `recorder:upload` is ABSENT on purpose — it is generated by the relay
 *  preload from a real file-input event, and accepting one from the page is
 *  exactly how a caller-chosen path reached the library copier. Anything not
 *  listed here (recovery decisions, manual-continue, check offers, and every
 *  other ipcMain.on channel in the app) is now unreachable from a page. */
export const PAGE_CHANNELS = [
  'recorder:event',
  'recorder:dialog',
  'recorder:picked',
  'recorder:pick-cancel'
] as const

export type PageChannel = (typeof PAGE_CHANNELS)[number]

/** Step types the observer itself can emit. Anything else is not something the
 *  recorder produces, so it can only have been made up. */
const OBSERVER_EVENT_TYPES = new Set(['click', 'hover', 'type', 'check', 'select', 'press'])

const DIALOG_KINDS = new Set(['alert', 'confirm', 'prompt'])

// Caps. Generous enough for real pages (a long textarea value, a deep frame
// chain), small enough that a hostile page cannot exhaust memory through them.
const MAX_STRING = 10_000
const MAX_TEXT = 1_000
const MAX_FRAME_DEPTH = 20
const MAX_DUP_KEYS = 16

export function isPageChannel(channel: unknown): channel is PageChannel {
  return typeof channel === 'string' && (PAGE_CHANNELS as readonly string[]).includes(channel)
}

// ── primitive readers ────────────────────────────────────────────────
// Each returns a CLEAN value or undefined. They never throw and never pass the
// caller's object through — the output is always freshly built.

function str(v: unknown, max = MAX_STRING): string | undefined {
  return typeof v === 'string' && v.length <= max ? v : undefined
}

function bool(v: unknown): boolean | undefined {
  return typeof v === 'boolean' ? v : undefined
}

function num(v: unknown): number | undefined {
  return typeof v === 'number' && Number.isFinite(v) ? v : undefined
}

function plainObject(v: unknown): Record<string, unknown> | null {
  return v && typeof v === 'object' && !Array.isArray(v) ? (v as Record<string, unknown>) : null
}

/** Drop keys whose value came back undefined, so the rebuilt object has only
 *  what actually validated. */
function compact(o: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {}
  for (const [k, v] of Object.entries(o)) if (v !== undefined) out[k] = v
  return out
}

// ── the element facts ────────────────────────────────────────────────
// The observer's description of the element that was interacted with. Rebuilt
// key by key: a page that adds `__proto__` or a function-valued field gets it
// dropped here rather than somewhere deeper in the selector engine.

function facts(v: unknown): Record<string, unknown> | undefined {
  const f = plainObject(v)
  if (!f) return undefined
  const tag = str(f.tag, 100)
  if (!tag) return undefined // an element with no tag is not an element

  const dupIn = plainObject(f.dup)
  let dup: Record<string, unknown> | undefined
  if (dupIn) {
    const cleaned: Record<string, unknown> = {}
    for (const key of Object.keys(dupIn).slice(0, MAX_DUP_KEYS)) {
      const d = plainObject(dupIn[key])
      if (!d) continue
      const count = num(d.count)
      const index = num(d.index)
      if (count === undefined || index === undefined) continue
      cleaned[key] = { count, index }
    }
    if (Object.keys(cleaned).length) dup = cleaned
  }

  const anchorIn = plainObject(f.anchor)
  let anchor: Record<string, unknown> | undefined
  if (anchorIn) {
    const css = str(anchorIn.css)
    const count = num(anchorIn.count)
    const index = num(anchorIn.index)
    if (css !== undefined && count !== undefined && index !== undefined) {
      anchor = { css, count, index }
    }
  }

  return compact({
    tag,
    testId: str(f.testId, MAX_TEXT),
    testIdAttr: f.testIdAttr === 'data-test' || f.testIdAttr === 'data-testid' ? f.testIdAttr : undefined,
    id: str(f.id, MAX_TEXT),
    name: str(f.name, MAX_TEXT),
    role: str(f.role, MAX_TEXT),
    type: str(f.type, MAX_TEXT),
    ariaLabel: str(f.ariaLabel, MAX_TEXT),
    title: str(f.title, MAX_TEXT),
    placeholder: str(f.placeholder, MAX_TEXT),
    text: str(f.text, MAX_TEXT),
    imgAlt: str(f.imgAlt, MAX_TEXT),
    inputValue: str(f.inputValue, MAX_STRING),
    labelText: str(f.labelText, MAX_TEXT),
    dup,
    anchor
  })
}

/**
 * The same element-facts check, for the ONE trusted channel that isn't a page
 * channel: `recorder:upload`, which the relay preload produces itself from an
 * isolated-world file event. Main validates it anyway — it owes that to itself
 * regardless of which of its own processes is talking.
 */
export function validateElementFacts(v: unknown): Record<string, unknown> | undefined {
  return facts(v)
}

/** The frame chain the event fired in — an array of { url, name }. */
function frame(v: unknown): { url: string; name?: string }[] | undefined {
  if (v === null || v === undefined) return undefined
  if (!Array.isArray(v) || v.length > MAX_FRAME_DEPTH) return undefined
  const out: { url: string; name?: string }[] = []
  for (const raw of v) {
    const f = plainObject(raw)
    if (!f) return undefined
    const url = str(f.url, 4_000)
    if (url === undefined) return undefined
    const name = str(f.name, MAX_TEXT)
    out.push(name === undefined ? { url } : { url, name })
  }
  return out
}

// ── the per-channel schemas ──────────────────────────────────────────

function recorderEvent(p: Record<string, unknown>): Record<string, unknown> | null {
  const type = str(p.type, 50)
  if (!type || !OBSERVER_EVENT_TYPES.has(type)) return null
  const f = facts(p.facts)
  if (!f) return null
  return compact({
    type,
    facts: f,
    value: str(p.value),
    secret: bool(p.secret),
    key: str(p.key, 50),
    frame: frame(p.frame)
  })
}

function recorderDialog(p: Record<string, unknown>): Record<string, unknown> | null {
  const kind = str(p.kind, 20)
  if (!kind || !DIALOG_KINDS.has(kind)) return null
  return compact({
    kind,
    message: str(p.message),
    value: str(p.value),
    accept: bool(p.accept)
  })
}

function recorderPicked(p: Record<string, unknown>): Record<string, unknown> | null {
  const f = facts(p.facts)
  if (!f) return null
  return compact({
    facts: f,
    text: str(p.text, MAX_TEXT),
    inputValue: str(p.inputValue),
    disabled: bool(p.disabled),
    checked: bool(p.checked),
    groupCount: num(p.groupCount),
    frame: frame(p.frame)
  })
}

/**
 * Validate one page-world message and return a CLEAN payload to forward, or
 * null to drop it.
 *
 * Returning a rebuilt object rather than the original is the point: after this
 * function, nothing downstream is holding a reference to anything the page
 * created, so no getter, proto trick or extra field survives the crossing.
 */
/**
 * The relay's whole decision, as a pure function.
 *
 * Lifted out of the preload so it can be tested without Electron or a DOM. What
 * is left in src/preload/recorder.ts is only what genuinely needs the browser:
 * reading `event.source` and calling `ipcRenderer.send`. Everything that decides
 * whether a message from the page is allowed to cross into Electron lives here,
 * where it is exercised from the attacker's side by the unit tests.
 *
 * Returns what to forward, or null to drop the message in silence — a hostile
 * page must not be able to tell the difference between "wrong nonce" and
 * "wrong shape".
 */
export function relayDecision(input: {
  /** The nonce main handed this tab's relay, or null when no session is armed. */
  sessionNonce: string | null
  /** Did this message come from a frame of this same tab? */
  sameTab: boolean
  /** The raw `event.data`, straight off the page. */
  data: unknown
}): { channel: PageChannel; payload: unknown } | null {
  const { sessionNonce, sameTab, data } = input
  if (!sameTab) return null

  const msg = plainObject(data)
  if (!msg || msg.__qaflow !== true) return null

  // No armed session means the page → IPC path is shut outright, which is the
  // state the app is in whenever the user is simply browsing.
  if (!sessionNonce || msg.nonce !== sessionNonce) return null

  if (!isPageChannel(msg.channel)) return null

  const payload = validatePageMessage(msg.channel, msg.payload)
  if (payload === null) return null

  return { channel: msg.channel, payload }
}

export function validatePageMessage(channel: string, payload: unknown): unknown | null {
  if (!isPageChannel(channel)) return null

  // The one channel with no payload at all.
  if (channel === 'recorder:pick-cancel') return undefined

  const p = plainObject(payload)
  if (!p) return null

  switch (channel) {
    case 'recorder:event':
      return recorderEvent(p)
    case 'recorder:dialog':
      return recorderDialog(p)
    case 'recorder:picked':
      return recorderPicked(p)
    default:
      return null
  }
}
