// Keep the test counts in the docs TRUE (audit finding QF-011).
//
//   node tools/doc-counts.mjs          rewrite the counts in README.md + FEATURES.md
//   node tools/doc-counts.mjs --check  exit 1 if they're stale (CI runs this)
//
// FEATURES.md said "66 unit tests, ~0.4 seconds" while the suite had 670 — a
// hand-typed number that nobody re-typed. The counts now live between
//   <!-- counts:start --> … <!-- counts:end -->
// markers, are computed from the real suites, and CI refuses a stale doc.
// The block sits inside <!-- prettier-ignore-start/end --> in each doc:
// prettier rewraps the one long generated line, this tool writes it back, and
// the two checks in CI would each fail on the other's output forever.
import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const run = (cmd) =>
  execSync(cmd, { cwd: root, encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'] })

// Unit tests: vitest's JSON report counts every test that exists.
const unitJson = JSON.parse(run('npx vitest run --reporter=json --silent'))
const unit = unitJson.numTotalTests
const unitFiles = unitJson.testResults.length

// Browser (DOM) tests: listing is enough — no browser needed, nothing runs.
const listing = run('npx playwright test --list')
const m = /Total: (\d+) tests? in (\d+) files?/.exec(listing)
if (!m) throw new Error('could not read the Playwright test count from --list')
const dom = Number(m[1])
const domFiles = Number(m[2])

const block =
  `<!-- counts:start -->\n` +
  `**Automated tests: ${unit} unit tests** (${unitFiles} files, \`npm test\`) and ` +
  `**${dom} browser tests** (${domFiles} files, \`npm run test:dom\`) — including a gate that ` +
  `generates specs with both exporters and runs them in real Playwright. ` +
  `_These numbers are generated by \`node tools/doc-counts.mjs\`; CI fails if they drift._\n` +
  `<!-- counts:end -->`

// Global: one doc can hold several blocks (FEATURES.md has two: the summary at
// the top and "How the app itself is tested"). A non-global regex filled only
// the first, so the second stayed empty and --check never noticed.
const RE = /<!-- counts:start -->[\s\S]*?<!-- counts:end -->/g
const check = process.argv.includes('--check')
let stale = []
for (const file of ['README.md', 'FEATURES.md']) {
  const path = join(root, file)
  const text = readFileSync(path, 'utf-8')
  const starts = text.split('<!-- counts:start -->').length - 1
  const found = (text.match(RE) || []).length
  if (!found) throw new Error(`${file} has no <!-- counts:start --> block`)
  if (found !== starts) throw new Error(`${file}: a <!-- counts:start --> has no matching end`)
  // Keep the file's own line endings. A Windows checkout (core.autocrlf) has
  // CRLF files; writing the block with bare LF left them mixed, which prettier
  // flags — and normalising them made THIS check report stale counts. Same
  // text either way once git stores it; this just lets both gates agree.
  const eol = text.includes('\r\n') ? '\r\n' : '\n'
  const next = text.replace(RE, block.replace(/\r?\n/g, eol))
  if (next === text) continue
  if (check) stale.push(file)
  else writeFileSync(path, next, 'utf-8')
}

if (check && stale.length) {
  console.error(`Stale test counts in: ${stale.join(', ')}. Run: node tools/doc-counts.mjs`)
  process.exit(1)
}
console.log(
  `unit=${unit} (${unitFiles} files)  dom=${dom} (${domFiles} files)  ${check ? 'docs are current' : 'docs updated'}`
)
